### ISSUE TITLE
Type of CheXpert dataset

### ISSUE THREAD

**Issue by AldusLorde** [Gofinge/CheXpert_Baseline_PyTorch#1]
Hi) Thank you for a such interesting implementation)
What kind of CheXpert dataset have you used (reduced image size or normal)?

**Comment by Gofinge** [comment]
reduced image size




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AldusLorde"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 晚上11:37
收件人:&nbsp;"Gofinge/CheXpert_Baseline_PyTorch"<CheXpert_Baseline_PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Gofinge/CheXpert_Baseline_PyTorch] Type of CheXpert dataset (#1)




Hi) Thank you for a such interesting implementation)
 What kind of CheXpert dataset have you used (reduced image size or normal)?

**Comment by AldusLorde** [comment]
Thank you)
