### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by AldusLorde** [Gofinge/CheXpert_Baseline_PyTorch#2]
Have you tried to train a model using 14 classes? According to your config.py, you used only 5 classes.

**Comment by Gofinge** [comment]
No, I just trained the five classes which evaluated in the baseline paper. you can have a try by changing the config.py. But I think there is not so much difference between training 5 classes and training 14 classes.

I write the baseline project to provide an easy framework which can be helpful to research the CheXpert DateSet and apply different methods, thanks for using it!

Best,
Xiaoyang

**Comment by AldusLorde** [comment]
I see, thank you for your answer)
