### ISSUE TITLE
Minor error in train.py

### ISSUE THREAD

**Issue by AldusLorde** [Gofinge/CheXpert_Baseline_PyTorch#3]
Hi again) In main.py, line 75, you have
`val_data = ChestXrayDataSet(opt.data_root, opt.valid_data_list_data_list, mode='train')`
Shouldn't it be opt.valid_data_list? I got an error on this line

**Comment by Gofinge** [comment]
Oh yes! Thanks for point out.

**Comment by AldusLorde** [comment]
Thank you for fixing it!
