### ISSUE TITLE
Dropout rate

### ISSUE THREAD

**Issue by AldusLorde** [Gofinge/CheXpert_Baseline_PyTorch#5]
Hi) According to your code, you use dropout rate of 0.9. It's a pretty high value (almost all outputs are dropped). Is it intentionally?

**Comment by Gofinge** [comment]
Nope, I think it was a mistake, I thought the p means kept rate. So it should be 0.1.

But my experiment result was really close to Paper result. Maybe most of the features in linear layer was close to zero. I will fix it. And you can try the method I said in issue 4 (change the num_classes in torctvision.model.densenet directly)
